#!/bin/sh
# Build a bootable eMMC/SD/NVMe image for the Raspberry Pi Compute Module 5.
# Runs inside the builder image (os/mixdocker.sh); needs no root.
#
#   p1  FAT32 "SSIBOOT"  config.txt, cmdline.txt, kernel_2712.img,
#                        ssi-initramfs.cpio.gz, bcm2712 device trees, overlays,
#                        ssi.conf, authorized_keys
#   p2  ext4  "ssi-data" /data: replicated store log, file blobs, keys
#
# Environment: SSI_CLUSTER, SSI_SECRET (generated once and kept in
# build/cm5/cluster.secret so every image of a cluster matches),
# SSI_DESKTOP (host:port), SSI_PASSWORD, SSI_AUTHORIZED_KEYS (path under os/),
# SSI_BOOT_MB (256), SSI_DATA_MB (2048).
set -eu
cd /os
b=build
out=$b/cm5
dts=$b/kernel/arch/arm64/boot/dts
boot_mb=${SSI_BOOT_MB:-256}
data_mb=${SSI_DATA_MB:-2048}
rm -rf "$out/boot" "$out"/*.img "$out"/*.vfat "$out"/*.ext4
mkdir -p "$out/boot/overlays"

if [ -n "${SSI_SECRET:-}" ]; then
  secret=$SSI_SECRET
elif [ -f "$out/cluster.secret" ]; then
  secret=$(cat "$out/cluster.secret")
else
  secret=$(head -c 24 /dev/urandom | base64)
  printf '%s\n' "$secret" > "$out/cluster.secret"
fi

cp boot/cm5/config.txt boot/cm5/cmdline.txt "$out/boot/"
cp "$b/kernel/arch/arm64/boot/Image" "$out/boot/kernel_2712.img"
cp "$b/ssi-initramfs.cpio.gz" "$out/boot/"
cp "$dts"/broadcom/bcm2712*.dtb "$out/boot/"
cp "$dts"/overlays/*.dtbo "$dts"/overlays/overlay_map.dtb "$out/boot/overlays/"
[ -f "$dts/overlays/hat_map.dtb" ] && cp "$dts/overlays/hat_map.dtb" "$out/boot/overlays/"
{
  echo "# Generated by mkimage-cm5.sh; see ssi.conf.example for every option."
  echo "cluster = ${SSI_CLUSTER:-ssi}"
  echo "secret = $secret"
  echo "net.eth0 = dhcp,linklocal"
  [ -n "${SSI_DESKTOP:-}" ] && echo "desktop = $SSI_DESKTOP"
  [ -n "${SSI_PASSWORD:-}" ] && echo "ssh.password = $SSI_PASSWORD"
  true
} > "$out/boot/ssi.conf"
cp boot/cm5/ssi.conf.example "$out/boot/"
[ -n "${SSI_AUTHORIZED_KEYS:-}" ] && cp "$SSI_AUTHORIZED_KEYS" "$out/boot/authorized_keys"

# FAT32 boot partition, populated with mtools.
mkfs.vfat -F 32 -n SSIBOOT -C "$out/boot.vfat" $((boot_mb * 1024)) >/dev/null
MTOOLS_SKIP_CHECK=1 mcopy -s -i "$out/boot.vfat" "$out/boot"/* ::/

# ext4 data partition (empty: the system lays it out on first boot).
mke2fs -q -t ext4 -L ssi-data -E root_owner=0:0 "$out/data.ext4" "${data_mb}M"

# MBR: p1 FAT32 (LBA) at 4 MiB, p2 Linux right after it.
img=$out/elixirssi-cm5.img
start1=8192
size1=$((boot_mb * 2048))
start2=$((start1 + size1))
size2=$((data_mb * 2048))
truncate -s $(( (start2 + size2) * 512 )) "$img"
printf 'label: dos\n%s,%s,c,*\n%s,%s,83\n' $start1 $size1 $start2 $size2 | sfdisk -q "$img"
dd if="$out/boot.vfat" of="$img" bs=512 seek=$start1 conv=notrunc status=none
dd if="$out/data.ext4" of="$img" bs=512 seek=$start2 conv=notrunc status=none
rm -f "$out/boot.vfat" "$out/data.ext4"
zstd -q -T0 -19 -f "$img" -o "$img.zst"
sha256sum "$img.zst" | sed "s|$out/||" > "$img.zst.sha256"
echo "cm5 image: $img ($(du -h "$img" | cut -f1) sparse), $img.zst ($(du -h "$img.zst" | cut -f1))"
